services:
  semiplay-api:
    build: ./server
    container_name: semiplay-api
    ports:
      - "127.0.0.1:3013:3001"
    environment:
      - FRONTEND_URL=https://semi.timuzkas.xyz
    env_file:
      - ./server/.env
    restart: unless-stopped

  semiplay-web:
    build: .
    container_name: semiplay-web
    ports:
      - "127.0.0.1:3012:80"
    depends_on:
      - semiplay-api
    restart: unless-stopped
